### ISSUE TITLE
Unity 2021.3 exception

### ISSUE THREAD

**Issue by NingInk** [NibbleByte/UnityWiseSVN#14] opened 2024-05-23 09:13 UTC
svn:global-ignores ~$*
![image](https://github.com/NibbleByte/UnityWiseSVN/assets/54977594/1fd49a93-e602-48db-b6be-926cc467f92a)

DirectoryNotFoundException: Could not find a part of the path
![image](https://github.com/NibbleByte/UnityWiseSVN/assets/54977594/5b6ad1a5-b749-4fc0-9fd4-647ad9e1ef5f)
![image](https://github.com/NibbleByte/UnityWiseSVN/assets/54977594/a8e02c27-0f70-4a19-bf34-8a0a4d58d948)

**Comment by NibbleByte** [comment] 2024-05-27 18:34
I can't reproduce this in any way. This may be due to me not having Chinese localization - I see that the project path includes some Chinese symbols. I tried having such symbols, but this resulted in other problems that I don't see in your screenshots. I see some strange things in your screenshots, but it is really hard for me to debug it without proper setup.

I'm afraid I can't help with this. If you try to debug it yourself and manage to find a good solution, please, let me know. Otherwise I'll close this ticket after some time.

**Comment by NingInk** [comment] 2024-06-03 05:44
Process. OutputDataReceived returned data will garbled.
I try to modify the ProcessStartInfo StandardOutputEncoding, but no normal results.  I'm at a loss for ideas.
I'm sorry to have delayed your time.
╮(╯▽╰)╭  Very helpless

**Comment by NibbleByte** [comment] 2024-06-03 09:39
Sorry I couldn't help. Maybe try naming your folders and files only with English letters.
Closing this ticket for now, if you find a solution, please let me know.

**Closed as completed by NibbleByte** 2024-06-03 09:39 UTC
